version: '2'

services:
  server:
    build: .
    command: ruby server.rb

  reader:
    build: .
    command: ruby reader.rb
    depends_on:
      - server

  incrementer:
    build: .
    command: ruby incrementer.rb
    depends_on:
      - server
